<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library[
<!ELEMENT library (books,records)>          	
<!ELEMENT books (book+)>                		
<!ELEMENT book (title)>                  		
<!ELEMENT title (#PCDATA)>                		
<!ELEMENT records (item*)>                		
<!ELEMENT item (date,person)>              	
<!ELEMENT date (#PCDATA)>               		
<!ELEMENT person EMPTY>
<!ATTLIST book bookid ID #REQUIRED>        	
<!ATTLIST person name CDATA #REQUIRED>
<!ATTLIST person borrowed IDREFS #REQUIRED>	
]>
<library>
<books>
<book bookid="1-1-2">
<title>XML详解</title>
</book>
<book bookid="1-1-3">
<title>Java程序设计入门</title>
</book>
<book bookid="1-1-1">
<title>c程序设计入门</title>
</book>
</books>
<records>
<item>
<date>2019-9-3</date>
<person name="anson" borrowed="1-1-2 1-1-1"/>
</item>
<item>
<date>2019-3-3</date>
<person name="John" borrowed="1-1-2 1-1-3"/>
</item>
</records>
</library>
